version: "3"
services:
    server:
        build: ./
        expose:
            - "3001"
        volumes:
            - .:/usr/src/app
        restart: always
    nginx:
        image: nginx:latest
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - /etc/letsencrypt:/etc/letsencrypt:ro
            - ./nginx.conf:/etc/nginx/nginx.conf:ro
        depends_on:
            - server
        restart: always
